<?php

namespace App;

use Carbon\Carbon;
use function foo\func;
use Illuminate\Database\Eloquent\Model;
use App\Helper\HasManyRelation;

class Invoice extends Model
{
    use HasManyRelation;

    protected $guarded = [];

    protected $with = ['customer', 'company', 'settings'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($invoice) {
            $invoice->settings->delete();
        });

    }

    public function items()
    {
        return $this->hasMany(Item::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function histories()
    {
        return $this->hasMany(InvoiceHistory::class);
    }

    public function payments()
    {
        return $this->hasMany(PaymentInvoice::class);
    }

    public function sentMails()
    {
        return $this->hasMany(InvoiceMail::class);
    }

    public function settings()
    {
        return $this->hasOne(InvoiceSettings::class);
    }

    public function createItems($items)
    {
        foreach ($items as $item) {
            $this->items()->create($item);
        }

        return $this;
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

   /* public function getInvoiceDateAttribute($value)
    {
        $date = Carbon::parse($value);

        if ($this->settings->date_format == 'dd.MM.yyyy') {
            $format = 'd.m.Y';
        } elseif ($this->settings->date_format == 'dd/MM/yyyy') {
            $format = 'd/m/Y';
        } elseif ($this->settings->date_format == 'MM/dd/yyyy') {
            $format = 'm/d/Y';
        } elseif ($this->settings->date_format == 'dd-MM-yyyy') {
            $format = 'd-m-Y';
        } else {
            $format = 'Y-m-d';
        }

        return $date->format($format);
    }

    public function getDueDateAttribute($value)
    {
        $date = Carbon::parse($value);

        if ($this->settings->date_format == 'dd.MM.yyyy') {
            $format = 'd.m.Y';
        } elseif ($this->settings->date_format == 'dd/MM/yyyy') {
            $format = 'd/m/Y';
        } elseif ($this->settings->date_format == 'MM/dd/yyyy') {
            $format = 'm/d/Y';
        } elseif ($this->settings->date_format == 'dd-MM-yyyy') {
            $format = 'd-m-Y';
        } else {
            $format = 'Y-m-d';
        }

        return $date->format($format);
    }*/
}
